ccflags-y += -Idrivers/media/platform/msm/camera_v2_n
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_ir_cut.o
