ccflags-y += -Idrivers/media/platform/msm/camera_v2_n
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
