ccflags-y += -Idrivers/media/platform/msm/camera_v2_n
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
