ccflags-y += -Idrivers/media/platform/msm/camera_v2_n
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_n/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
